
The following have been reloaded with a version change:
  1) fsl/5.0.2 => fsl/5.0.9

Freesurfer loaded but not setup. Now run: source $FREESURFER_HOME/SetUpFreeSurfer.sh

Be sure that your $SUBJECTS_DIR variable is set to a directory you have write 
access to, or provide a subjects dir argument to commands that require it. 


Launcher: Setup complete.

------------- SUMMARY ---------------
   Number of hosts:    1
   Working directory:  .
   Processes per host: 2
   Total processes:    2
   Total jobs:         1
   Scheduling method:  dynamic

-------------------------------------
Launcher: Starting parallel tasks...
Warning: Permanently added '[nid01204]:6999,[10.128.4.189]:6999' (RSA) to the list of known hosts.
grep: invalid max count
Launcher: Task 1 running job 1 on nid01204 (python /work/02885/gshearre/lonestar/setup_subject/setup_subjectgrace.py --getdata --keepdata --osirix_username davis --osirix_password eatthisnotthat --studyname sugar_brain -s sb_0069 --dcm2nii --motcorr --betfunc --fm --fs-subdir /corral-repl/utexas/poldracklab/data/sugar_brain/freesurfer --fsrecon -o)
Launcher: Task 0 running job Done on nid01204 ()
Launcher: Job Done completed in 0 seconds.
Launcher: Task 0 done. Exiting.
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): sweetn.irc.utexas.edu
starting from grace's working directory
subdir /corral-repl/utexas/poldracklab/data/sugar_brain/sb_0069 already exists
overwriting...
Traceback (most recent call last):
  File "/work/02885/gshearre/lonestar/setup_subject/setup_subjectgrace.py", line 600, in <module>
    download_from_osirix(args,subdir)
  File "/work/02885/gshearre/lonestar/setup_subject/setup_subjectgrace.py", line 333, in download_from_osirix
    ziphandle.extractall(os.path.join(subdir,'raw',args['subcode']))
  File "/opt/apps/intel16/python/2.7.10/lib/python2.7/zipfile.py", line 1040, in extractall
    self.extract(zipinfo, path, pwd)
  File "/opt/apps/intel16/python/2.7.10/lib/python2.7/zipfile.py", line 1028, in extract
    return self._extract_member(member, path, pwd)
  File "/opt/apps/intel16/python/2.7.10/lib/python2.7/zipfile.py", line 1084, in _extract_member
    shutil.copyfileobj(source, target)
  File "/opt/apps/intel16/python/2.7.10/lib/python2.7/shutil.py", line 49, in copyfileobj
    buf = fsrc.read(length)
  File "/opt/apps/intel16/python/2.7.10/lib/python2.7/zipfile.py", line 632, in read
    data = self.read1(n - len(buf))
  File "/opt/apps/intel16/python/2.7.10/lib/python2.7/zipfile.py", line 684, in read1
    max(n - len_readbuffer, self.MIN_READ_SIZE)
zlib.error: Error -3 while decompressing: invalid code lengths set
Launcher: Job 1 completed in 2222 seconds.
Launcher: Task 1 done. Exiting.
Launcher: Done. Job exited without errors
